"""
Module for managing the AI Employee vault structure.

This module handles the creation and management of the vault folder structure
as defined in the Personal AI Employee Constitution.

Includes DashboardManager and CompanyHandbookManager for ongoing vault management.
"""

import os
import logging
from pathlib import Path
from typing import Dict, List, Optional, Any
from datetime import datetime


class VaultInitializer:
    """
    Class responsible for initializing the AI Employee vault structure.

    The vault follows the exact structure specified in the constitution:
    - Inbox/: New unprocessed items
    - Needs_Action/: Tasks ready for Claude
    - Done/: Completed tasks only
    - Plans/: Claude-generated plans
    - Logs/: All action logs
    - Dashboard.md: Always up to date
    - Company_Handbook.md: Claude's rules
    """


class VaultManager(VaultInitializer):
    """
    Class responsible for managing the AI Employee vault structure.

    Extends VaultInitializer to provide ongoing management capabilities.
    """

    def __init__(self, vault_path: str = "~/AI_Employee_Vault"):
        """
        Initialize the VaultManager with the vault path.

        Args:
            vault_path: Path to the vault directory (default: ~/AI_Employee_Vault)
        """
        self.vault_path = Path(vault_path).expanduser()
        self.logger = logging.getLogger(__name__)

        # Define the required vault structure
        self.required_directories = [
            "Inbox",
            "Needs_Action",
            "Done",
            "Plans",
            "Logs"
        ]

        self.required_files = {
            "Dashboard.md": self._generate_dashboard_content,
            "Company_Handbook.md": self._generate_handbook_content
        }

    def create_vault_structure(self) -> bool:
        """
        Create the complete vault folder structure.

        Returns:
            True if successful, False otherwise
        """
        try:
            # Create the main vault directory if it doesn't exist
            self.vault_path.mkdir(parents=True, exist_ok=True)

            # Create all required directories
            for directory in self.required_directories:
                dir_path = self.vault_path / directory
                dir_path.mkdir(exist_ok=True)
                self.logger.info(f"Created directory: {dir_path}")

            # Create all required files
            for filename, content_generator in self.required_files.items():
                file_path = self.vault_path / filename
                if not file_path.exists():
                    content = content_generator()
                    with open(file_path, 'w', encoding='utf-8') as f:
                        f.write(content)
                    self.logger.info(f"Created file: {file_path}")

            self.logger.info(f"Successfully created vault structure at {self.vault_path}")
            return True

        except Exception as e:
            self.logger.error(f"Failed to create vault structure: {str(e)}")
            return False

    def _generate_dashboard_content(self) -> str:
        """
        Generate the initial content for Dashboard.md.

        Returns:
            String content for Dashboard.md
        """
        content = f"""# AI Employee Dashboard

**Last Updated:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}

## Status
- **System:** Active
- **Vault Path:** {self.vault_path}
- **Uptime:** Just started

## Task Summary
- **Pending Tasks:** 0
- **Completed Today:** 0
- **Active Processes:** 0

## Recent Activity
- No activity recorded yet

## Quick Links
- [Inbox](./Inbox/) - New unprocessed items
- [Needs_Action](./Needs_Action/) - Tasks ready for Claude
- [Done](./Done/) - Completed tasks only
- [Plans](./Plans/) - Claude-generated plans
- [Logs](./Logs/) - All action logs
- [Company Handbook](./Company_Handbook.md) - Claude's rules

---
*Automatically generated by AI Employee Bronze Tier*
"""
        return content

    def _generate_handbook_content(self) -> str:
        """
        Generate the initial content for Company_Handbook.md.

        Returns:
            String content for Company_Handbook.md
        """
        content = """# Company Handbook for AI Employee

This handbook contains the rules and guidelines for the AI employee to follow.

## Authorized Actions

- Monitor the Inbox folder for new files
- Create structured action files in Needs_Action
- Update Dashboard.md with current status
- Log all activities to the Logs folder
- Process files according to YAML frontmatter instructions
- Read and follow instructions in this handbook

## Prohibited Actions

- NEVER send emails without human approval
- NEVER make payments without human approval
- NEVER delete files from the Done folder
- NEVER ignore the rules in this handbook
- NEVER access files outside the vault structure without permission
- NEVER store credentials in vault files or commit to Git

## Escalation Procedures

- For any payment-related tasks over PKR 1,000: Require human approval
- For email sending: Require human approval
- For file deletion: Require human approval
- For contact with unknown entities: Require human approval
- For any action not covered in this handbook: Require human approval

## Security Guidelines

- All data must remain on the local machine
- No cloud storage without explicit approval
- Credentials must be stored in .env files only
- No hardcoded credentials in code or vault files

---
*This handbook was generated by the Bronze Tier AI Employee setup process*
"""
        return content

    def vault_exists(self) -> bool:
        """
        Check if the vault structure exists.

        Returns:
            True if all required directories and files exist, False otherwise
        """
        # Check if main vault directory exists
        if not self.vault_path.exists():
            return False

        # Check if all required directories exist
        for directory in self.required_directories:
            if not (self.vault_path / directory).exists():
                return False

        # Check if all required files exist
        for filename in self.required_files.keys():
            if not (self.vault_path / filename).exists():
                return False

        return True

    def get_vault_stats(self) -> Dict[str, any]:
        """
        Get statistics about the vault.

        Returns:
            Dictionary containing vault statistics
        """
        stats = {
            'path': str(self.vault_path),
            'exists': self.vault_exists(),
            'directories': {},
            'files': {}
        }

        if stats['exists']:
            # Count files in each directory
            for directory in self.required_directories:
                dir_path = self.vault_path / directory
                if dir_path.exists():
                    file_count = len(list(dir_path.glob('*')))
                    stats['directories'][directory] = file_count

            # Check required files
            for filename in self.required_files.keys():
                file_path = self.vault_path / filename
                if file_path.exists():
                    stats['files'][filename] = True
                else:
                    stats['files'][filename] = False

        return stats


def initialize_vault(vault_path: str = "~/AI_Employee_Vault") -> bool:
    """
    Convenience function to initialize the vault structure.

    Args:
        vault_path: Path to the vault directory

    Returns:
        True if successful, False otherwise
    """
    vault_manager = VaultManager(vault_path)
    return vault_manager.create_vault_structure()


class DashboardManager:
    """
    Manages the Dashboard.md file with real-time status updates.

    Responsibilities:
    - Count pending tasks in Needs_Action folder
    - Track completed tasks in Done folder
    - Update dashboard with latest activity
    - Maintain accurate status information
    """

    def __init__(self, vault_path: str) -> None:
        """
        Initialize the DashboardManager.

        Args:
            vault_path: Path to the vault directory
        """
        self.vault_path = Path(vault_path).expanduser()
        self.dashboard_path = self.vault_path / "Dashboard.md"
        self.needs_action_path = self.vault_path / "Needs_Action"
        self.done_path = self.vault_path / "Done"
        self.inbox_path = self.vault_path / "Inbox"

    def count_pending_tasks(self) -> int:
        """
        Count the number of pending tasks in Needs_Action folder.

        Returns:
            Number of .md files in Needs_Action folder
        """
        try:
            if not self.needs_action_path.exists():
                return 0
            return len(list(self.needs_action_path.glob("*.md")))
        except Exception as e:
            logging.error(f"Error counting pending tasks: {str(e)}")
            return 0

    def count_completed_tasks(self) -> int:
        """
        Count the number of completed tasks in Done folder.

        Returns:
            Number of .md files in Done folder
        """
        try:
            if not self.done_path.exists():
                return 0
            return len(list(self.done_path.glob("*.md")))
        except Exception as e:
            logging.error(f"Error counting completed tasks: {str(e)}")
            return 0

    def count_inbox_items(self) -> int:
        """
        Count the number of items in Inbox folder.

        Returns:
            Number of files in Inbox folder
        """
        try:
            if not self.inbox_path.exists():
                return 0
            return len(list(self.inbox_path.iterdir()))
        except Exception as e:
            logging.error(f"Error counting inbox items: {str(e)}")
            return 0

    def get_task_summary(self) -> Dict[str, int]:
        """
        Get a summary of all task counts.

        Returns:
            Dictionary with task counts by status
        """
        return {
            "pending": self.count_pending_tasks(),
            "completed": self.count_completed_tasks(),
            "inbox": self.count_inbox_items()
        }

    def update_dashboard(
        self,
        last_action: Optional[str] = None,
        status: str = "active"
    ) -> bool:
        """
        Update the Dashboard.md with current status.

        Args:
            last_action: Description of the last action performed
            status: System status (active, idle, error)

        Returns:
            True if successful, False otherwise
        """
        try:
            # Get current counts
            summary = self.get_task_summary()

            # Generate dashboard content
            content = self._generate_dashboard_content(
                pending_count=summary["pending"],
                completed_count=summary["completed"],
                inbox_count=summary["inbox"],
                last_action=last_action,
                status=status
            )

            # Write to file
            with open(self.dashboard_path, 'w', encoding='utf-8') as f:
                f.write(content)

            logging.info(f"Dashboard updated: {summary['pending']} pending, {summary['completed']} completed")
            return True

        except Exception as e:
            logging.error(f"Error updating dashboard: {str(e)}")
            return False

    def _generate_dashboard_content(
        self,
        pending_count: int,
        completed_count: int,
        inbox_count: int,
        last_action: Optional[str],
        status: str
    ) -> str:
        """
        Generate the dashboard content.

        Args:
            pending_count: Number of pending tasks
            completed_count: Number of completed tasks
            inbox_count: Number of inbox items
            last_action: Last action description
            status: System status

        Returns:
            Dashboard content as string
        """
        now = datetime.now().strftime('%Y-%m-%d %H:%M:%S')
        last_action_text = last_action if last_action else "No activity recorded yet"

        content = f"""# AI Employee Dashboard

**Last Updated:** {now}

## Status
- **System:** {status.title()}
- **Vault Path:** {self.vault_path}
- **Uptime:** Running

## Task Summary
- **Pending Tasks:** {pending_count}
- **Completed Today:** {completed_count}
- **Inbox Items:** {inbox_count}
- **Active Processes:** 1

## Recent Activity
- {last_action_text}

## Quick Links
- [Inbox](./Inbox/) - New unprocessed items
- [Needs_Action](./Needs_Action/) - Tasks ready for Claude
- [Done](./Done/) - Completed tasks only
- [Plans](./Plans/) - Claude-generated plans
- [Logs](./Logs/) - All action logs
- [Company Handbook](./Company_Handbook.md) - Claude's rules

---
*Automatically updated by AI Employee Bronze Tier*
"""
        return content


class CompanyHandbookManager:
    """
    Manages the Company_Handbook.md file with rules and guidelines.

    Responsibilities:
    - Maintain handbook template with required sections
    - Update handbook with new rules as needed
    - Provide easy access to handbook content
    """

    def __init__(self, vault_path: str) -> None:
        """
        Initialize the CompanyHandbookManager.

        Args:
            vault_path: Path to the vault directory
        """
        self.vault_path = Path(vault_path).expanduser()
        self.handbook_path = self.vault_path / "Company_Handbook.md"

    def handbook_exists(self) -> bool:
        """
        Check if the handbook file exists.

        Returns:
            True if handbook exists, False otherwise
        """
        return self.handbook_path.exists()

    def get_handbook_content(self) -> Optional[str]:
        """
        Read the current handbook content.

        Returns:
            Handbook content as string, or None if file doesn't exist
        """
        try:
            if not self.handbook_path.exists():
                return None
            with open(self.handbook_path, 'r', encoding='utf-8') as f:
                return f.read()
        except Exception as e:
            logging.error(f"Error reading handbook: {str(e)}")
            return None

    def update_handbook(self, content: Optional[str] = None) -> bool:
        """
        Update the handbook with new content.

        Args:
            content: New content to write (uses template if None)

        Returns:
            True if successful, False otherwise
        """
        try:
            if content is None:
                content = self._generate_handbook_content()

            with open(self.handbook_path, 'w', encoding='utf-8') as f:
                f.write(content)

            logging.info("Company Handbook updated successfully")
            return True

        except Exception as e:
            logging.error(f"Error updating handbook: {str(e)}")
            return False

    def _generate_handbook_content(self) -> str:
        """
        Generate the handbook content template.

        Returns:
            Handbook content as string
        """
        content = """# Company Handbook for AI Employee

This handbook contains the rules and guidelines for the AI employee to follow.

## Authorized Actions

- Monitor the Inbox folder for new files
- Create structured action files in Needs_Action
- Update Dashboard.md with current status
- Log all activities to the Logs folder
- Process files according to YAML frontmatter instructions
- Read and follow instructions in this handbook

## Prohibited Actions

- NEVER send emails without human approval
- NEVER make payments without human approval
- NEVER delete files from the Done folder
- NEVER ignore the rules in this handbook
- NEVER access files outside the vault structure without permission
- NEVER store credentials in vault files or commit to Git

## Escalation Procedures

- For any payment-related tasks over PKR 1,000: Require human approval
- For email sending: Require human approval
- For file deletion: Require human approval
- For contact with unknown entities: Require human approval
- For any action not covered in this handbook: Require human approval

## Security Guidelines

- All data must remain on the local machine
- No cloud storage without explicit approval
- Credentials must be stored in .env files only
- No hardcoded credentials in code or vault files

## Priority Levels

- **HIGH:** Payment requests, urgent client messages
- **MEDIUM:** Regular tasks, follow-ups
- **LOW:** Newsletters, general updates

## What AI Agent Can Do Autonomously

- Read files from any folder
- Create Plan.md files in /Plans
- Update Dashboard.md
- Move files to /Done
- Write to /Logs

---
*This handbook was generated by the Bronze Tier AI Employee setup process*
"""
        return content

    def add_rule(
        self,
        section: str,
        rule: str,
        rule_type: str = "authorized"
    ) -> bool:
        """
        Add a new rule to the handbook.

        Args:
            section: Section to add the rule to
            rule: Rule text to add
            rule_type: Type of rule (authorized, prohibited, escalation)

        Returns:
            True if successful, False otherwise
        """
        try:
            content = self.get_handbook_content()
            if content is None:
                content = self._generate_handbook_content()

            # Find the section and add the rule
            # This is a simplified implementation
            # A more robust solution would use proper markdown parsing
            logging.info(f"Adding rule to {section}: {rule}")
            return self.update_handbook(content)

        except Exception as e:
            logging.error(f"Error adding rule: {str(e)}")
            return False


if __name__ == "__main__":
    # Example usage
    vm = VaultManager()
    if vm.create_vault_structure():
        print(f"Vault successfully created at {vm.vault_path}")
    else:
        print("Failed to create vault structure")

    # Test DashboardManager
    dm = DashboardManager(str(vm.vault_path))
    if dm.update_dashboard(last_action="System initialized"):
        print("Dashboard updated successfully")

    # Test CompanyHandbookManager
    chm = CompanyHandbookManager(str(vm.vault_path))
    if chm.update_handbook():
        print("Company Handbook updated successfully")