"""Ralph Wiggum Loop Implementation for Gold Tier AI Employee.

This module implements the "Ralph Wiggum" pattern - a stop hook that keeps
the AI agent working autonomously until a task is complete.

Pattern:
1. Orchestrator creates state file with prompt
2. Agent works on task
3. Agent tries to exit
4. Stop hook checks: Is task file in /Done?
5. YES → Allow exit (complete)
6. NO → Block exit, re-inject prompt (loop continues)
7. Repeat until complete or max iterations

Reference: https://github.com/anthropics/claude-code/tree/main/.claude/plugins/ralph-wiggum
"""
import os
import time
import logging
from pathlib import Path
from datetime import datetime
from typing import Optional, Dict, Any, List
from dataclasses import dataclass
from enum import Enum

from .vault_manager import vault
from .audit_logger import audit_logger
from .error_recovery import health_monitor, HealthStatus

logger = logging.getLogger(__name__)


class TaskStatus(Enum):
    """Task status enum."""
    PENDING = "pending"
    IN_PROGRESS = "in_progress"
    COMPLETED = "completed"
    FAILED = "failed"
    CANCELLED = "cancelled"


@dataclass
class TaskState:
    """Represents the state of a task being processed."""
    task_id: str
    created: datetime
    updated: datetime
    status: TaskStatus
    progress: int  # 0-100
    current_step: int
    total_steps: int
    max_iterations: int
    current_iteration: int
    domain: str
    priority: str
    prompt: str
    last_output: Optional[str]
    error_message: Optional[str]
    recovery_point: Optional[str]
    correlation_id: Optional[str]
    
    def to_dict(self) -> Dict[str, Any]:
        """Convert to dictionary."""
        return {
            "task_id": self.task_id,
            "created": self.created.isoformat(),
            "updated": self.updated.isoformat(),
            "status": self.status.value,
            "progress": self.progress,
            "current_step": self.current_step,
            "total_steps": self.total_steps,
            "max_iterations": self.max_iterations,
            "current_iteration": self.current_iteration,
            "domain": self.domain,
            "priority": self.priority,
            "prompt": self.prompt,
            "last_output": self.last_output,
            "error_message": self.error_message,
            "recovery_point": self.recovery_point,
            "correlation_id": self.correlation_id
        }
    
    def to_markdown(self) -> str:
        """Convert to markdown format for state file."""
        return f"""---
type: task_state
task_id: {self.task_id}
created: {self.created.isoformat()}
updated: {self.updated.isoformat()}
status: {self.status.value}
progress: {self.progress}
current_step: {self.current_step}
total_steps: {self.total_steps}
max_iterations: {self.max_iterations}
current_iteration: {self.current_iteration}
domain: {self.domain}
priority: {self.priority}
correlation_id: {self.correlation_id or 'N/A'}
---

# Task State: {self.task_id}

## Current Status
- **Progress**: {self.progress}%
- **Current Step**: {self.current_step} of {self.total_steps}
- **Iteration**: {self.current_iteration} of {self.max_iterations}
- **Status**: {self.status.value.upper()}

## Task Description
{self.prompt}

## Steps
| # | Step | Status | Notes |
|---|------|--------|-------|
| 1 | Step 1 | {"✅" if self.current_step > 1 else "🔄" if self.current_step == 1 else "⏳"} | |
| 2 | Step 2 | {"✅" if self.current_step > 2 else "🔄" if self.current_step == 2 else "⏳"} | |
| 3 | Step 3 | {"✅" if self.current_step > 3 else "🔄" if self.current_step == 3 else "⏳"} | |

## Last Output
{self.last_output or 'No output yet'}

## Errors
{self.error_message or 'None'}

## Recovery Point
{self.recovery_point or 'None'}

---
*Generated by Ralph Wiggum Loop at {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}*
"""


class RalphWiggumLoop:
    """Ralph Wiggum Loop implementation.
    
    This class implements the stop hook pattern that keeps the AI agent
    working autonomously until a task is complete.
    
    Usage:
        loop = RalphWiggumLoop()
        result = loop.run_until_complete(
            prompt="Process all emails in inbox",
            max_iterations=10
        )
    """
    
    def __init__(
        self,
        max_iterations: int = 10,
        check_interval: int = 5,
        completion_signal: str = "TASK_COMPLETE"
    ):
        """Initialize Ralph Wiggum Loop.
        
        Args:
            max_iterations: Maximum iterations before giving up
            check_interval: Seconds between completion checks
            completion_signal: Signal that indicates task completion
        """
        self.max_iterations = max_iterations
        self.check_interval = check_interval
        self.completion_signal = completion_signal
        
        self.active_tasks: Dict[str, TaskState] = {}
        self.logger = logging.getLogger(self.__class__.__name__)
        
        self.logger.info(
            f"Ralph Wiggum Loop initialized: "
            f"max_iterations={max_iterations}, "
            f"check_interval={check_interval}s"
        )
    
    def create_task(
        self,
        prompt: str,
        domain: str = "business",
        priority: str = "normal",
        total_steps: int = 5,
        correlation_id: Optional[str] = None
    ) -> str:
        """Create a new task state.
        
        Args:
            prompt: Task prompt/description
            domain: Task domain (business, personal, finance)
            priority: Task priority
            total_steps: Estimated total steps
            correlation_id: Optional correlation ID
            
        Returns:
            Task ID
        """
        task_id = f"task_{datetime.now().strftime('%Y%m%d_%H%M%S')}_{os.getpid()}"
        
        state = TaskState(
            task_id=task_id,
            created=datetime.now(),
            updated=datetime.now(),
            status=TaskStatus.PENDING,
            progress=0,
            current_step=0,
            total_steps=total_steps,
            max_iterations=self.max_iterations,
            current_iteration=0,
            domain=domain,
            priority=priority,
            prompt=prompt,
            last_output=None,
            error_message=None,
            recovery_point=None,
            correlation_id=correlation_id
        )
        
        self.active_tasks[task_id] = state
        
        # Create state file
        self._save_task_state(state)
        
        # Audit log
        audit_logger.log(
            action_type="ralph_wiggum.create_task",
            actor="RalphWiggumLoop",
            actor_type="system",
            domain=domain,
            subdomain="orchestration",
            target=task_id,
            parameters={
                "prompt": prompt,
                "max_iterations": self.max_iterations
            },
            result="success",
            correlation_id=correlation_id
        )
        
        self.logger.info(f"Created task: {task_id}")
        return task_id
    
    def check_completion(self, task_id: str) -> bool:
        """Check if task is complete.
        
        Checks if task file has been moved to /Done folder.
        
        Args:
            task_id: Task ID to check
            
        Returns:
            True if complete, False otherwise
        """
        if task_id not in self.active_tasks:
            return False
        
        state = self.active_tasks[task_id]
        
        # Check if status is completed
        if state.status == TaskStatus.COMPLETED:
            return True
        
        # Check if file moved to Done folder
        done_folder = vault.paths.done
        done_files = list(done_folder.glob(f"*{task_id}*"))
        
        if done_files:
            self._update_task_state(task_id, status=TaskStatus.COMPLETED, progress=100)
            return True
        
        # Check if max iterations reached
        if state.current_iteration >= state.max_iterations:
            self._update_task_state(task_id, status=TaskStatus.FAILED)
            return True
        
        return False
    
    def should_continue(self, task_id: str) -> bool:
        """Check if loop should continue.
        
        This is the "stop hook" - returns False if task is complete.
        
        Args:
            task_id: Task ID
            
        Returns:
            True if should continue, False if should stop
        """
        is_complete = self.check_completion(task_id)
        
        if is_complete:
            self.logger.info(f"Task {task_id} complete, stopping loop")
            return False
        
        return True
    
    def re_inject_prompt(self, task_id: str) -> str:
        """Re-inject prompt for next iteration.
        
        Args:
            task_id: Task ID
            
        Returns:
            Prompt for next iteration
        """
        if task_id not in self.active_tasks:
            raise ValueError(f"Task not found: {task_id}")
        
        state = self.active_tasks[task_id]
        
        # Increment iteration
        state.current_iteration += 1
        state.updated = datetime.now()
        
        # Create re-injection prompt
        prompt = f"""
[RALPH WIGGUM LOOP - Iteration {state.current_iteration}/{state.max_iterations}]

Continue working on this task. Do not stop until complete.

Original Task:
{state.prompt}

Current Progress: {state.progress}%
Current Step: {state.current_step}/{state.total_steps}

Last Output:
{state.last_output or 'No output yet'}

Instructions:
1. Continue from where you left off
2. If you encounter an error, try a different approach
3. Mark task as complete by moving the state file to /Done folder
4. Output "{self.completion_signal}" when task is complete

Do not stop until the task is fully complete!
"""
        
        # Save updated state
        self._save_task_state(state)
        
        self.logger.info(
            f"Re-injecting prompt for task {task_id} "
            f"(iteration {state.current_iteration}/{state.max_iterations})"
        )
        
        return prompt
    
    def update_progress(
        self,
        task_id: str,
        progress: int,
        current_step: int,
        output: Optional[str] = None
    ):
        """Update task progress.
        
        Args:
            task_id: Task ID
            progress: Progress percentage (0-100)
            current_step: Current step number
            output: Optional output from agent
        """
        if task_id not in self.active_tasks:
            return
        
        state = self.active_tasks[task_id]
        state.progress = progress
        state.current_step = current_step
        state.updated = datetime.now()
        
        if output:
            state.last_output = output
        
        # Update recovery point
        state.recovery_point = f"Step {current_step}, {progress}% complete"
        
        self._save_task_state(state)
        self.logger.debug(f"Updated progress for {task_id}: {progress}%")
    
    def mark_complete(self, task_id: str, output: Optional[str] = None):
        """Mark task as complete.
        
        Args:
            task_id: Task ID
            output: Optional final output
        """
        if task_id not in self.active_tasks:
            return
        
        state = self.active_tasks[task_id]
        state.status = TaskStatus.COMPLETED
        state.progress = 100
        state.updated = datetime.now()
        
        if output:
            state.last_output = output
        
        # Move state file to Done folder
        self._move_to_done(task_id)
        
        # Audit log
        audit_logger.log(
            action_type="ralph_wiggum.complete_task",
            actor="RalphWiggumLoop",
            actor_type="system",
            domain=state.domain,
            target=task_id,
            parameters={
                "iterations": state.current_iteration,
                "final_progress": state.progress
            },
            result="success",
            correlation_id=state.correlation_id
        )
        
        self.logger.info(f"Task {task_id} marked as complete")
    
    def mark_failed(self, task_id: str, error_message: str):
        """Mark task as failed.
        
        Args:
            task_id: Task ID
            error_message: Error message
        """
        if task_id not in self.active_tasks:
            return
        
        state = self.active_tasks[task_id]
        state.status = TaskStatus.FAILED
        state.error_message = error_message
        state.updated = datetime.now()
        
        self._save_task_state(state)
        
        # Audit log
        audit_logger.log(
            action_type="ralph_wiggum.fail_task",
            actor="RalphWiggumLoop",
            actor_type="system",
            domain=state.domain,
            target=task_id,
            parameters={"error": error_message},
            result="failed"
        )
        
        self.logger.error(f"Task {task_id} failed: {error_message}")
    
    def get_task_state(self, task_id: str) -> Optional[TaskState]:
        """Get current task state.
        
        Args:
            task_id: Task ID
            
        Returns:
            Task state or None
        """
        return self.active_tasks.get(task_id)
    
    def _save_task_state(self, state: TaskState):
        """Save task state to file.
        
        Args:
            state: Task state to save
        """
        # Create state file in Plans folder
        state_file = vault.paths.plans / f"TASK_STATE_{state.task_id}.md"
        state_file.write_text(state.to_markdown())
    
    def _update_task_state(self, task_id: str, **kwargs):
        """Update task state.
        
        Args:
            task_id: Task ID
            **kwargs: Fields to update
        """
        if task_id not in self.active_tasks:
            return
        
        state = self.active_tasks[task_id]
        
        for key, value in kwargs.items():
            if hasattr(state, key):
                setattr(state, key, value)
        
        state.updated = datetime.now()
        self._save_task_state(state)
    
    def _move_to_done(self, task_id: str):
        """Move task state file to Done folder.
        
        Args:
            task_id: Task ID
        """
        state_file = vault.paths.plans / f"TASK_STATE_{task_id}.md"
        
        if state_file.exists():
            dest = vault.paths.done / f"TASK_STATE_{task_id}.md"
            state_file.rename(dest)
            self.logger.debug(f"Moved task state to Done: {task_id}")
    
    def run_until_complete(
        self,
        prompt: str,
        agent_func: callable,
        domain: str = "business",
        priority: str = "normal",
        max_iterations: Optional[int] = None
    ) -> Dict[str, Any]:
        """Run agent until task is complete.
        
        This is the main loop that keeps re-injecting prompts until
        the task is complete or max iterations is reached.
        
        Args:
            prompt: Initial prompt
            agent_func: Function to call with prompt
            domain: Task domain
            priority: Task priority
            max_iterations: Override max iterations
            
        Returns:
            Result dictionary
        """
        if max_iterations:
            self.max_iterations = max_iterations
        
        # Create task
        task_id = self.create_task(
            prompt=prompt,
            domain=domain,
            priority=priority
        )
        
        self.logger.info(f"Starting Ralph Wiggum loop for task {task_id}")
        
        iteration = 0
        while self.should_continue(task_id):
            iteration += 1
            
            # Get prompt for this iteration
            if iteration == 1:
                current_prompt = prompt
            else:
                current_prompt = self.re_inject_prompt(task_id)
            
            # Call agent function
            try:
                output = agent_func(current_prompt)
                
                # Update progress (agent should report progress)
                # This is simplified - in real implementation, parse output for progress
                progress = min(iteration * 20, 90)  # Estimate progress
                self.update_progress(task_id, progress, iteration, output)
                
            except Exception as e:
                self.logger.error(f"Iteration {iteration} failed: {e}")
                self._update_task_state(task_id, error_message=str(e))
            
            # Small delay to prevent tight loop
            time.sleep(self.check_interval)
        
        # Get final state
        final_state = self.get_task_state(task_id)
        
        return {
            "task_id": task_id,
            "completed": final_state.status == TaskStatus.COMPLETED,
            "iterations": final_state.current_iteration,
            "final_status": final_state.status.value,
            "final_output": final_state.last_output
        }


# ==================== AGENT SKILLS ====================

from agents import function_tool

# Global loop instance
ralph_wiggum_loop = RalphWiggumLoop(max_iterations=10, check_interval=5)


@function_tool()
def ensure_task_completion(
    task_description: str,
    max_iterations: int = 10,
    domain: str = "business"
) -> str:
    """
    Ensure a task completes using Ralph Wiggum loop.
    
    This skill keeps the agent working until the task is fully complete.
    
    Args:
        task_description: Description of task to complete
        max_iterations: Maximum iterations before giving up
        domain: Task domain (business, personal, finance)
    
    Returns:
        Task completion status
    """
    # Create task
    task_id = ralph_wiggum_loop.create_task(
        prompt=task_description,
        domain=domain,
        max_iterations=max_iterations
    )
    
    return (
        f"Task created: {task_id}\n"
        f"Max iterations: {max_iterations}\n"
        f"Domain: {domain}\n\n"
        f"The agent will continue working on this task until complete "
        f"or max iterations ({max_iterations}) is reached."
    )


@function_tool()
def check_task_status(task_id: str) -> str:
    """
    Check status of a task.
    
    Args:
        task_id: Task ID to check
    
    Returns:
        Task status information
    """
    state = ralph_wiggum_loop.get_task_state(task_id)
    
    if not state:
        return f"Task not found: {task_id}"
    
    return (
        f"Task: {state.task_id}\n"
        f"Status: {state.status.value.upper()}\n"
        f"Progress: {state.progress}%\n"
        f"Step: {state.current_step}/{state.total_steps}\n"
        f"Iteration: {state.current_iteration}/{state.max_iterations}\n"
        f"Last Output: {state.last_output or 'None'}\n"
        f"Error: {state.error_message or 'None'}"
    )


@function_tool()
def update_task_progress(
    task_id: str,
    progress: int,
    current_step: int,
    output: str
) -> str:
    """
    Update task progress.
    
    Args:
        task_id: Task ID
        progress: Progress percentage (0-100)
        current_step: Current step number
        output: Current output from agent
    
    Returns:
        Confirmation of update
    """
    ralph_wiggum_loop.update_progress(task_id, progress, current_step, output)
    return f"Updated task {task_id}: {progress}% complete, step {current_step}"


@function_tool()
def mark_task_complete(task_id: str, final_output: str) -> str:
    """
    Mark task as complete.
    
    Args:
        task_id: Task ID
        final_output: Final output
    
    Returns:
        Confirmation
    """
    ralph_wiggum_loop.mark_complete(task_id, final_output)
    return f"Task {task_id} marked as complete"


@function_tool()
def get_active_tasks() -> str:
    """
    Get list of active tasks.
    
    Returns:
        List of active tasks
    """
    active = [
        task for task in ralph_wiggum_loop.active_tasks.values()
        if task.status in [TaskStatus.PENDING, TaskStatus.IN_PROGRESS]
    ]
    
    if not active:
        return "No active tasks"
    
    result = "Active Tasks:\n\n"
    for task in active:
        result += (
            f"- {task.task_id}: {task.progress}% complete, "
            f"step {task.current_step}/{task.total_steps}\n"
        )
    
    return result


# Export for use
__all__ = [
    'RalphWiggumLoop',
    'ralph_wiggum_loop',
    'TaskState',
    'TaskStatus',
    'ensure_task_completion',
    'check_task_status',
    'update_task_progress',
    'mark_task_complete',
    'get_active_tasks'
]
