"""Vault management module for Gold Tier AI Employee system."""
import os
import json
from pathlib import Path
from datetime import datetime
from typing import Dict, List, Optional, Any
from dataclasses import dataclass
from ..config.settings import settings


@dataclass
class VaultPaths:
    """Defines all vault paths for the AI Employee system."""

    vault_path: Path
    inbox: Path
    needs_action: Path
    in_progress: Path
    plans: Path
    pending_approval: Path
    approved: Path
    rejected: Path
    done: Path
    logs: Path
    accounting: Path
    updates: Path
    signals: Path
    briefings: Path
    dashboard_md: Path
    company_handbook_md: Path
    business_goals_md: Path


class VaultManager:
    """Manages the Obsidian vault for the AI Employee system."""

    def __init__(self, vault_path: Optional[str] = None):
        self.vault_path = Path(vault_path or settings.VAULT_PATH)
        self.paths = self._setup_paths()
        self._ensure_directories()

    def _setup_paths(self) -> VaultPaths:
        """Setup all required vault paths."""
        return VaultPaths(
            vault_path=self.vault_path,
            inbox=self.vault_path / "Inbox",
            needs_action=self.vault_path / "Needs_Action",
            in_progress=self.vault_path / "In_Progress",
            plans=self.vault_path / "Plans",
            pending_approval=self.vault_path / "Pending_Approval",
            approved=self.vault_path / "Approved",
            rejected=self.vault_path / "Rejected",
            done=self.vault_path / "Done",
            logs=self.vault_path / "Logs",
            accounting=self.vault_path / "Accounting",
            updates=self.vault_path / "Updates",
            signals=self.vault_path / "Signals",
            briefings=self.vault_path / "Briefings",
            dashboard_md=self.vault_path / "Dashboard.md",
            company_handbook_md=self.vault_path / "Company_Handbook.md",
            business_goals_md=self.vault_path / "Business_Goals.md"
        )

    def _ensure_directories(self):
        """Ensure all required directories exist."""
        for path in [
            self.paths.inbox,
            self.paths.needs_action,
            self.paths.in_progress,
            self.paths.plans,
            self.paths.pending_approval,
            self.paths.approved,
            self.paths.rejected,
            self.paths.done,
            self.paths.logs,
            self.paths.accounting,
            self.paths.updates,
            self.paths.signals,
            self.paths.briefings
        ]:
            path.mkdir(parents=True, exist_ok=True)

    def create_dashboard_if_missing(self):
        """Create Dashboard.md if it doesn't exist."""
        if not self.paths.dashboard_md.exists():
            content = f"""# 📊 AI Employee Dashboard

**Last Updated**: {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}
**Status**: 🟢 Running

## Quick Stats
| Metric | Value |
|--------|-------|
| Pending Items | 0 |
| In Progress | 0 |
| Awaiting Approval | 0 |
| Completed Today | 0 |

## Recent Activity
- [{datetime.now().strftime("%Y-%m-%d %H:%M")}] System started

## Pending Approvals
None

## Active Projects
None

## Alerts
- ℹ️ System operational

---
*Generated by AI Employee v0.3.0*
"""
            self.paths.dashboard_md.write_text(content)

    def create_company_handbook_if_missing(self):
        """Create Company_Handbook.md if it doesn't exist."""
        if not self.paths.company_handbook_md.exists():
            content = """# 📖 Company Handbook - Rules of Engagement

**Last Updated**: 2026-03-12

## Communication Rules
1. Always be polite and professional
2. Response time target: < 24 hours
3. Flag urgent messages immediately
4. Never send bulk emails without approval

## Financial Rules
1. Auto-approve payments < $50 to known recipients
2. Always require approval for:
   - New recipients
   - Payments > $100
   - Recurring payments > $50/month
3. Flag transactions > $500 for review

## Social Media Rules
1. Auto-post scheduled content
2. Require approval for:
   - Replies to comments
   - Direct messages
   - Sensitive topics

## Privacy Rules
1. Never share credentials
2. Log all actions
3. Encrypt sensitive data
4. Review logs weekly

## Escalation Rules
1. Unknown sender + large amount = Alert immediately
2. Legal/medical topics = Require human review
3. Emotional content = Flag for human handling
"""
            self.paths.company_handbook_md.write_text(content)

    def create_business_goals_if_missing(self):
        """Create Business_Goals.md if it doesn't exist."""
        if not self.paths.business_goals_md.exists():
            content = """# 🎯 Business Goals - Q1 2026

**Last Updated**: 2026-03-12
**Review Frequency**: Weekly

## Revenue Targets
| Metric | Target | Current | Status |
|--------|--------|---------|--------|
| Monthly Revenue | $10,000 | $0 | 🔴 0% |
| MTD | $0 | $0 | 🔴 Not Started |

## Key Metrics to Track
| Metric | Target | Alert Threshold |
|--------|--------|-----------------|
| Client response time | < 24 hours | > 48 hours |
| Invoice payment rate | > 90% | < 80% |
| Software costs | < $500/month | > $600/month |

## Active Projects
None

## Subscription Audit Rules
Flag for review if:
- No login in 30 days
- Cost increased > 20%
- Duplicate functionality with another tool
"""
            self.paths.business_goals_md.write_text(content)

    def initialize_vault(self):
        """Initialize the vault with required files."""
        self.create_dashboard_if_missing()
        self.create_company_handbook_if_missing()
        self.create_business_goals_if_missing()

    def get_file_count_in_folder(self, folder_name: str) -> int:
        """Get count of files in a specific folder."""
        folder_path = getattr(self.paths, folder_name, None)
        if not folder_path or not folder_path.exists():
            return 0
        return len(list(folder_path.glob("*")))

    def create_action_file(self,
                          category: str,
                          filename: str,
                          content: str,
                          priority: str = "normal") -> Path:
        """Create an action file in the Needs_Action folder."""
        category_path = self.paths.needs_action / category
        category_path.mkdir(exist_ok=True)

        file_path = category_path / filename
        file_path.write_text(content)

        return file_path

    def move_file(self, source: Path, destination_folder: str) -> Path:
        """Move a file to a destination folder."""
        dest_path = getattr(self.paths, destination_folder)
        if not dest_path.exists():
            dest_path.mkdir(parents=True, exist_ok=True)

        dest_file = dest_path / source.name
        source.rename(dest_file)

        return dest_file

    def log_action(self,
                   action_type: str,
                   target: str,
                   parameters: Dict[str, Any],
                   result: str,
                   approved_by: Optional[str] = None) -> Path:
        """Log an action to the logs directory."""
        timestamp = datetime.now().strftime("%Y-%m-%d")
        log_file = self.paths.logs / f"{timestamp}.jsonl"

        log_entry = {
            "timestamp": datetime.now().isoformat(),
            "action_type": action_type,
            "actor": "ai_employee_gold",
            "target": target,
            "parameters": parameters,
            "approval_status": "approved" if approved_by else "auto",
            "approved_by": approved_by,
            "result": result
        }

        with open(log_file, "a", encoding="utf-8") as f:
            f.write(json.dumps(log_entry) + "\n")

        return log_file

    def read_dashboard(self) -> str:
        """Read the dashboard content."""
        if self.paths.dashboard_md.exists():
            return self.paths.dashboard_md.read_text(encoding="utf-8")
        return ""

    def update_dashboard(self, content: str):
        """Update the dashboard with new content."""
        self.paths.dashboard_md.write_text(content, encoding="utf-8")


# Global vault instance
vault = VaultManager()